name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Build and run daemon
      shell: bash
      run: |
        docker build -t newrelic-daemon -f Dockerfile.daemon .
        docker run --rm \
          -d \
          -v $PWD/newrelic-logs:/var/log/newrelic \
          -v /tmp:/tmp \
          newrelic-daemon
    - name: Rust Action
      uses: icepuma/rust-action@1.41.0
      with:
        args: cargo fmt -- --check && cargo clippy -- -Dwarnings && cargo test
